name: 'Deploy MVP Phase 1'
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'dev'

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  codesets:
    runs-on: ubuntu-latest
    steps:
      - run: |
          gh workflow run build-test-deploy.yml -R Virtual-Finland-Development/codesets -f environment=${{ inputs.environment }}
          sleep 5
          gh run watch -R Virtual-Finland-Development/codesets $(gh run list -R Virtual-Finland-Development/codesets -w workflow.yaml -L1 --json databaseId --jq .[0].databaseId)
  monitoring:
    runs-on: ubuntu-latest
    needs: [codesets]
    steps:
      - run: |
          gh workflow run publish-codesets-dashboard-to-environment.yml -R Virtual-Finland-Development/monitoring -f environment=${{ inputs.environment }}
          sleep 5
          gh run watch -R Virtual-Finland-Development/monitoring $(gh run list -R Virtual-Finland-Development/monitoring -w workflow.yaml -L1 --json databaseId --jq .[0].databaseId)
