name: 'Deploy MVP Phase 1'
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        type: environment
        required: true
        default: 'dev'

env:
  GH_TOKEN: ${{ secrets.VFD_PROJECTS_PAT }}

concurrency:
  group: deployment-${{ inputs.environment }}
  cancel-in-progress: true

jobs:
  infrastructure:
    runs-on: ubuntu-latest
    steps:
      - uses: Virtual-Finland-Development/projects/.github/actions/deployment@main
        with:
          environment: ${{ inputs.environment }}
          repository: infrastructure
          workflow: test.yml
  codesets:
    runs-on: ubuntu-latest
    needs: infrastructure
    steps:
      - uses: Virtual-Finland-Development/projects/.github/actions/deployment@main
        with:
          environment: ${{ inputs.environment }}
          repository: codesets
          workflow: build-test-deploy.yml
  monitoring:
    runs-on: ubuntu-latest
    needs: codesets
    steps:
      - uses: Virtual-Finland-Development/projects/.github/actions/deployment@main
        with:
          environment: ${{ inputs.environment }}
          repository: monitoring
          workflow: publish-codesets-dashboard-to-environment.yml
