name: "Deploy MVP Phase 2"
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Deployment environment"
        type: environment
        required: true
        default: "dev"

env:
  GH_TOKEN: ${{ secrets.VFD_PROJECTS_PAT }}

concurrency:
  group: deployment-${{ inputs.environment }}
  cancel-in-progress: true

jobs:
  infrastructure:
    name: "Infrastructure on ${{ inputs.environment }}"
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: Virtual-Finland-Development/projects/.github/actions/deployment@main
        with:
          environment: ${{ inputs.environment }}
          repository: infrastructure
          workflow: test.yml
  alerts:
    name: "Alerts on ${{ inputs.environment }}"
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    needs: infrastructure
    steps:
      - uses: Virtual-Finland-Development/projects/.github/actions/deployment@main
        with:
          environment: ${{ inputs.environment }}
          repository: monitoring
          workflow: publish-cloudwatch-logs-alerts-to-environment.yml
  escoApi:
    name: "Esco API on ${{ inputs.environment }}"
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    needs: [infrastructure, alerts]
    steps:
      - uses: Virtual-Finland-Development/projects/.github/actions/deployment@main
        with:
          environment: ${{ inputs.environment }}
          repository: esco-api
          workflow: deployment.yml
  codesets:
    name: "Codesets on ${{ inputs.environment }}"
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    needs: [infrastructure, alerts, escoApi]
    steps:
      - uses: Virtual-Finland-Development/projects/.github/actions/deployment@main
        with:
          environment: ${{ inputs.environment }}
          repository: codesets
          workflow: build-test-deploy.yml
  usersApi:
    name: "Users API on ${{ inputs.environment }}"
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    needs: [infrastructure, alerts, codesets]
    steps:
      - uses: Virtual-Finland-Development/projects/.github/actions/deployment@main
        with:
          environment: ${{ inputs.environment }}
          repository: users-api
          workflow: deploy-to-environment.yml
  mvpApp:
    name: "MVP App on ${{ inputs.environment }}"
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    needs: [infrastructure, alerts, codesets, usersApi]
    steps:
      - uses: Virtual-Finland-Development/projects/.github/actions/deployment@main
        with:
          environment: ${{ inputs.environment }}
          repository: access-finland
          workflow: deploy-af-mvp.yml
  monitoring:
    name: "Monitoring on ${{ inputs.environment }}"
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    needs: [infrastructure, codesets, usersApi, mvpApp]
    steps:
      - uses: Virtual-Finland-Development/projects/.github/actions/deployment@main
        with:
          environment: ${{ inputs.environment }}
          repository: monitoring
          workflow: publish-cloudfront-log-forwarder-to-environment.yml
      - uses: Virtual-Finland-Development/projects/.github/actions/deployment@main
        with:
          environment: ${{ inputs.environment }}
          repository: monitoring
          workflow: publish-codesets-dashboard-to-environment.yml
      - uses: Virtual-Finland-Development/projects/.github/actions/deployment@main
        with:
          environment: ${{ inputs.environment }}
          repository: monitoring
          workflow: publish-aws-dashboard-to-environment.yml
