name: "Deploy MVP Phase 1"
on:
  workflow_dispatch:
    inputs:
      environment:
        description: Deployment environment
        type: environment
        required: true
        default: "dev"
      deploy_monitoring:
        description: Deploy monitoring
        type: boolean
        required: false
        default: true
  workflow_call:
    inputs:
      environment:
        description: Deployment environment
        type: string
        required: true
      deploy_monitoring:
        description: Deploy monitoring
        type: boolean
        required: false
        default: true

concurrency:
  group: deployment-${{ inputs.environment }}
  cancel-in-progress: true

jobs:
  infrastructure:
    name: "Infrastructure on ${{ inputs.environment }}"
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: Virtual-Finland-Development/projects/.github/actions/deployment@main
        with:
          environment: ${{ inputs.environment }}
          repository: infrastructure
          workflow: test.yml
  alerts:
    name: "Alerts on ${{ inputs.environment }}"
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    needs: infrastructure
    steps:
      - uses: Virtual-Finland-Development/projects/.github/actions/deployment@main
        with:
          environment: ${{ inputs.environment }}
          repository: monitoring
          workflow: publish-cloudwatch-logs-alerts-to-environment.yml
  escoApi:
    name: "Esco API on ${{ inputs.environment }}"
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    needs: [infrastructure, alerts]
    steps:
      - uses: Virtual-Finland-Development/projects/.github/actions/deployment@main
        with:
          environment: ${{ inputs.environment }}
          repository: esco-api
          workflow: deployment.yml
  monitoring:
    name: "Monitoring on ${{ inputs.environment }}"
    if : ${{ github.event.inputs.deploy_monitoring == 'true' }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    needs:  [infrastructure, alerts, escoApi]
    steps:
      - uses: Virtual-Finland-Development/projects/.github/actions/deployment@main
        with:
          environment: ${{ inputs.environment }}
          repository: monitoring
          workflow: publish-esco-api-dashboard-to-environment.yml