name: 'Deploy MVP Phase 1'
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        type: environment
        required: true
        default: 'dev'

env:
  GH_TOKEN: ${{ secrets.VFD_PROJECTS_PAT }}

jobs:
  codesets:
    runs-on: ubuntu-latest
    steps:
      - uses: ./actions/deployment@main
        with:
          environment: ${{ inputs.environment }}
          repository: codesets
          workflow: build-test-deploy.yml
  monitoring:
    runs-on: ubuntu-latest
    needs: [codesets]
    steps:
      - uses: ./actions/deployment@main
        with:
          environment: ${{ inputs.environment }}
          repository: monitoring
          workflow: publish-codesets-dashboard-to-environment.yml
