name: "Deploy MVP Phase 2"
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Deployment environment"
        type: environment
        required: true
        default: "dev"

concurrency:
  group: phase2-${{ inputs.environment }}
  cancel-in-progress: true

jobs:
  deploy-phase1:
        uses: Virtual-Finland-Development/projects/.github/workflows/phase1.yml@main
        secrets: inherit
        with:
          environment: ${{ inputs.environment }}
  codesets:
    name: "Codesets on ${{ inputs.environment }}"
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    needs: [deploy-phase1]
    steps:
      - uses: Virtual-Finland-Development/projects/.github/actions/deployment@main
        with:
          environment: ${{ inputs.environment }}
          repository: codesets
          workflow: build-test-deploy.yml
  usersApi:
    name: "Users API on ${{ inputs.environment }}"
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    needs: [deploy-phase1, codesets]
    steps:
      - uses: Virtual-Finland-Development/projects/.github/actions/deployment@main
        with:
          environment: ${{ inputs.environment }}
          repository: users-api
          workflow: deploy-to-environment.yml
  mvpApp:
    name: "MVP App on ${{ inputs.environment }}"
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    needs: [deploy-phase1, codesets, usersApi]
    steps:
      - uses: Virtual-Finland-Development/projects/.github/actions/deployment@main
        with:
          environment: ${{ inputs.environment == 'dev' && 'mvp-dev' || inputs.environment }}
          repository: access-finland
          workflow: deploy-af-mvp.yml
  monitoring:
    name: "Monitoring on ${{ inputs.environment }}"
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    needs: [deploy-phase1, codesets, usersApi, mvpApp]
    steps:
      - uses: Virtual-Finland-Development/projects/.github/actions/deployment@main
        with:
          environment: ${{ inputs.environment }}
          repository: monitoring
          workflow: publish-esco-api-dashboard-to-environment.yml
      - uses: Virtual-Finland-Development/projects/.github/actions/deployment@main
        with:
          environment: ${{ inputs.environment }}
          repository: monitoring
          workflow: publish-cloudfront-log-forwarder-to-environment.yml
      - uses: Virtual-Finland-Development/projects/.github/actions/deployment@main
        with:
          environment: ${{ inputs.environment }}
          repository: monitoring
          workflow: publish-accessfinland-dashboard-to-environment.yml
