name: 'Deploy MVP Phase 2'
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'dev'

env:
  GH_TOKEN: ${{ secrets.VFD_PROJECTS_PAT }}
  
jobs:
  codesets:
    runs-on: ubuntu-latest
    steps:
      - uses: ./actions/deployment@main
        with:
          environment: ${{ inputs.environment }}
          repository: codesets
          workflow: build-test-deploy.yml
  usersApi:
    runs-on: ubuntu-latest
    needs: [codesets]
    steps:
      - uses: ./actions/deployment@main
        with:
          environment: ${{ inputs.environment }}
          repository: users-api
          workflow: deploy-to-environment.yml
  mvpApp:
    runs-on: ubuntu-latest
    needs: [codesets]
    steps:
      - uses: ./actions/deployment@main
        with:
          environment: ${{ inputs.environment }}
          repository: virtual-finland
          workflow: test-and-deploy-mvp.yml
  monitoring:
    runs-on: ubuntu-latest
    needs: [codesets]
    steps:
      - uses: ./actions/deployment@main
        with:
          environment: ${{ inputs.environment }}
          repository: monitoring
          workflow: publish-codesets-dashboard-to-environment.yml