name: 'Deploy MVP Phase 2'
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'dev'

env:
  GH_TOKEN: ${{ secrets.VFD_PROJECTS_PAT }}

concurrency:
  group: deployment-${{ inputs.environment }}
  cancel-in-progress: true

jobs:
  infrastructure:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: Virtual-Finland-Development/projects/.github/actions/deployment@main
        with:
          environment: ${{ inputs.environment }}
          repository: infrastructure
          workflow: test.yml
  codesets:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    needs: [infrastructure]
    steps:
      - uses: Virtual-Finland-Development/projects/.github/actions/deployment@main
        with:
          environment: ${{ inputs.environment }}
          repository: codesets
          workflow: build-test-deploy.yml
  usersApi:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    needs: [infrastructure, codesets]
    steps:
      - uses: Virtual-Finland-Development/projects/.github/actions/deployment@main
        with:
          environment: ${{ inputs.environment }}
          repository: users-api
          workflow: deploy-to-environment.yml
  mvpApp:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    needs: [infrastructure, codesets]
    steps:
      - uses: Virtual-Finland-Development/projects/.github/actions/deployment@main
        with:
          environment: ${{ inputs.environment }}
          repository: virtual-finland
          workflow: test-and-deploy-mvp.yml
  monitoring:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    needs: [infrastructure, codesets, usersApi, mvpApp]
    steps:
      - uses: Virtual-Finland-Development/projects/.github/actions/deployment@main
        with:
          environment: ${{ inputs.environment }}
          repository: monitoring
          workflow: publish-cloudfront-log-forwarder-to-environment.yml
      - uses: Virtual-Finland-Development/projects/.github/actions/deployment@main
        with:
          environment: ${{ inputs.environment }}
          repository: monitoring
          workflow: publish-codesets-dashboard-to-environment.yml
      - uses: Virtual-Finland-Development/projects/.github/actions/deployment@main
        with:
          environment: ${{ inputs.environment }}
          repository: monitoring
          workflow: publish-aws-dashboard-to-environment.yml